import React from 'react';

export interface InstrumentRow {
  id: string;
  name: string;
  symbol: string;
  price: number;
  decimals: number;
  change: number; // percentage, e.g. +0.85
  return1M: number; // percentage, e.g. +21.77
  rolVolume: number; // e.g. 1.34
  rsi: number; // e.g. 56.2
  marketCap: string; // e.g. "$1.54T"
  signal: {
    type: 'lock' | 'neutral' | 'buy';
    text: string; // e.g. ">50%", "Neutral 45%"
  };
  iconType: string;
  iconBg?: string;
  iconColor?: string;
}

export interface VolumeCategoryItem {
  name: string;
  volume: string; // e.g. "48.52 B"
  rawVolume: number; // for bar width percentage
  color?: string;
}

export interface MarketCategory {
  id: string;
  name: string;
  statValue: string; // "$200.5T"
  statChange: string; // "+0.45%"
  activity: string; // "+$4.15"
  fearGreedScore: number; // 72
  fearGreedLabel: string; // "Greed"
  fearGreedColor: string; // "#BEF226"
  entryVal: string; // "+$2.0T +0.45%"
  stopVal: string; // "+$2.0T +0.45%"
  allLiquidation: string; // "$600.40 M"
  longVal: string; // "$450.0M"
  shortVal: string; // "$150.4M"
  openInterest: string; // "+$2.0T +0.45%"
  volumeVal: string; // "+$2.0T +0.45%"
  totalResults: number; // e.g. 463
  chartPoints: number[]; // 24 points
  volumeComparison: {
    '1D': VolumeCategoryItem[];
    '1W': VolumeCategoryItem[];
    '1M': VolumeCategoryItem[];
    '1Y': VolumeCategoryItem[];
  };
  instruments: InstrumentRow[];
}

export const MARKET_CATEGORIES: MarketCategory[] = [
  {
    id: 'crypto',
    name: 'Crypto',
    statValue: '$200.5T',
    statChange: '+0.45%',
    activity: '+$4.15',
    fearGreedScore: 72,
    fearGreedLabel: 'Greed',
    fearGreedColor: '#BEF226',
    entryVal: '+$2.0T  +0.45%',
    stopVal: '+$2.0T  +0.45%',
    allLiquidation: '$600.40 M',
    longVal: '$450.0M',
    shortVal: '$150.4M',
    openInterest: '+$2.0T  +0.45%',
    volumeVal: '+$2.0T  +0.45%',
    totalResults: 463,
    chartPoints: [
      12, 14, 15, 13, 16, 18, 22, 28, 25, 23, 20, 24, 27, 30, 26, 29, 34, 38, 36, 42, 40, 44, 43, 46,
    ],
    volumeComparison: {
      '1D': [
        { name: 'Stablecoin', volume: '48.52 B', rawVolume: 100 },
        { name: 'Bitcoin', volume: '28.45 B', rawVolume: 62 },
        { name: 'De-Fi', volume: '$6.12 B', rawVolume: 15 },
        { name: 'Meme', volume: '$4.89 B', rawVolume: 12 },
        { name: 'Layer 2', volume: '$3.15 B', rawVolume: 8 },
        { name: 'AI & DePIN', volume: '$1.78 B', rawVolume: 4.5 },
        { name: 'Game-Fi', volume: '$842.6 M', rawVolume: 2.2 },
      ],
      '1W': [
        { name: 'Stablecoin', volume: '312.4 B', rawVolume: 100 },
        { name: 'Bitcoin', volume: '194.2 B', rawVolume: 64 },
        { name: 'De-Fi', volume: '$42.8 B', rawVolume: 16 },
        { name: 'Meme', volume: '$31.6 B', rawVolume: 11 },
        { name: 'Layer 2', volume: '$22.1 B', rawVolume: 8 },
        { name: 'AI & DePIN', volume: '$12.4 B', rawVolume: 4.8 },
        { name: 'Game-Fi', volume: '$5.9 B', rawVolume: 2.4 },
      ],
      '1M': [
        { name: 'Stablecoin', volume: '1.24 T', rawVolume: 100 },
        { name: 'Bitcoin', volume: '810.5 B', rawVolume: 67 },
        { name: 'De-Fi', volume: '$180.2 B', rawVolume: 17 },
        { name: 'Meme', volume: '$125.4 B', rawVolume: 12 },
        { name: 'Layer 2', volume: '$95.0 B', rawVolume: 8.5 },
        { name: 'AI & DePIN', volume: '$52.1 B', rawVolume: 5 },
        { name: 'Game-Fi', volume: '$24.6 B', rawVolume: 2.5 },
      ],
      '1Y': [
        { name: 'Stablecoin', volume: '14.8 T', rawVolume: 100 },
        { name: 'Bitcoin', volume: '9.4 T', rawVolume: 65 },
        { name: 'De-Fi', volume: '$2.1 T', rawVolume: 18 },
        { name: 'Meme', volume: '$1.4 T', rawVolume: 12 },
        { name: 'Layer 2', volume: '$1.1 T', rawVolume: 9 },
        { name: 'AI & DePIN', volume: '$620 B', rawVolume: 5.2 },
        { name: 'Game-Fi', volume: '$310 B', rawVolume: 2.8 },
      ],
    },
    instruments: [
      {
        id: 'btc',
        name: 'Bitcoin',
        symbol: 'BTC/USD',
        price: 77204.0,
        decimals: 2,
        change: 0.85,
        return1M: 21.77,
        rolVolume: 1.34,
        rsi: 56.2,
        marketCap: '$1.54T',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'btc',
        iconBg: '#F7931A',
        iconColor: '#FFFFFF',
      },
      {
        id: 'eth',
        name: 'Ethereum',
        symbol: 'ETH/USD',
        price: 2514.85,
        decimals: 2,
        change: 3.17,
        return1M: 33.78,
        rolVolume: 1.72,
        rsi: 58.7,
        marketCap: '$297.46B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'eth',
        iconBg: '#1E293B',
        iconColor: '#627EEA',
      },
      {
        id: 'bnb',
        name: 'Binance',
        symbol: 'BNB/USD',
        price: 726.51,
        decimals: 2,
        change: 2.55,
        return1M: 19.03,
        rolVolume: 1.41,
        rsi: 55.4,
        marketCap: '$94.34B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'bnb',
        iconBg: '#F3BA2F',
        iconColor: '#FFFFFF',
      },
      {
        id: 'xmr',
        name: 'Monero',
        symbol: 'XMR/USD',
        price: 521.83,
        decimals: 2,
        change: 2.68,
        return1M: 32.99,
        rolVolume: 1.28,
        rsi: 61.3,
        marketCap: '$9.56B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'xmr',
        iconBg: '#FF6600',
        iconColor: '#FFFFFF',
      },
      {
        id: 'ltc',
        name: 'Litecoin',
        symbol: 'LTC/USD',
        price: 53.28,
        decimals: 2,
        change: 2.25,
        return1M: 18.72,
        rolVolume: 1.16,
        rsi: 57.1,
        marketCap: '$4.04B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'ltc',
        iconBg: '#345D9D',
        iconColor: '#FFFFFF',
      },
      {
        id: 'xrp',
        name: 'Ripple',
        symbol: 'XRP/USD',
        price: 1.36,
        decimals: 2,
        change: 2.26,
        return1M: 35.29,
        rolVolume: 1.53,
        rsi: 54.6,
        marketCap: '$83.88B',
        signal: { type: 'neutral', text: 'Neutral 45%' },
        iconType: 'xrp',
        iconBg: '#23292F',
        iconColor: '#FFFFFF',
      },
      {
        id: 'pol',
        name: 'Polygon',
        symbol: 'POL/USD',
        price: 0.0974,
        decimals: 4,
        change: 5.74,
        return1M: 30.68,
        rolVolume: 1.88,
        rsi: 59.8,
        marketCap: '$986M',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'pol',
        iconBg: '#8247E5',
        iconColor: '#FFFFFF',
      },
      {
        id: 'avax',
        name: 'Avalance',
        symbol: 'AVAX/USD',
        price: 7.46,
        decimals: 2,
        change: 0.2,
        return1M: 18.09,
        rolVolume: 0.92,
        rsi: 48.9,
        marketCap: '$3.21B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'avax',
        iconBg: '#E84142',
        iconColor: '#FFFFFF',
      },
      {
        id: 'sol',
        name: 'Solana',
        symbol: 'SOL/USD',
        price: 102.39,
        decimals: 2,
        change: 3.81,
        return1M: 35.41,
        rolVolume: 1.67,
        rsi: 60.7,
        marketCap: '$57.83B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'sol',
        iconBg: '#00FFA3',
        iconColor: '#000000',
      },
      {
        id: 'uni',
        name: 'Uniswap',
        symbol: 'UNI/USD',
        price: 6.01,
        decimals: 2,
        change: 1.01,
        return1M: 68.14,
        rolVolume: 2.06,
        rsi: 67.2,
        marketCap: '$3.71B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'uni',
        iconBg: '#FF007A',
        iconColor: '#FFFFFF',
      },
      {
        id: 'link',
        name: 'Chainlink',
        symbol: 'LINK/USD',
        price: 14.85,
        decimals: 2,
        change: 4.12,
        return1M: 28.5,
        rolVolume: 1.45,
        rsi: 62.3,
        marketCap: '$8.94B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'link',
        iconBg: '#375BD2',
        iconColor: '#FFFFFF',
      },
      {
        id: 'ada',
        name: 'Cardano',
        symbol: 'ADA/USD',
        price: 0.428,
        decimals: 3,
        change: 1.84,
        return1M: 22.4,
        rolVolume: 1.22,
        rsi: 53.4,
        marketCap: '$14.80B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'ada',
        iconBg: '#0033AD',
        iconColor: '#FFFFFF',
      },
    ],
  },
  {
    id: 'forex',
    name: 'Forex',
    statValue: '$200.5T',
    statChange: '+0.45%',
    activity: '+$4.15',
    fearGreedScore: 72,
    fearGreedLabel: 'Greed',
    fearGreedColor: '#BEF226',
    entryVal: '+$2.0T  +0.45%',
    stopVal: '+$2.0T  +0.45%',
    allLiquidation: '$600.40 M',
    longVal: '$450.0M',
    shortVal: '$150.4M',
    openInterest: '+$2.0T  +0.45%',
    volumeVal: '+$2.0T  +0.45%',
    totalResults: 463,
    chartPoints: [
      20, 22, 21, 23, 25, 24, 26, 28, 27, 29, 31, 30, 32, 35, 33, 34, 36, 35, 37, 39, 38, 40, 41, 42,
    ],
    volumeComparison: {
      '1D': [
        { name: 'Major Pairs', volume: '3.82 T', rawVolume: 100 },
        { name: 'Minor Pairs', volume: '1.45 T', rawVolume: 42 },
        { name: 'Crosses', volume: '$920 B', rawVolume: 26 },
        { name: 'Commodity FX', volume: '$640 B', rawVolume: 18 },
        { name: 'Exotic Pairs', volume: '$410 B', rawVolume: 12 },
        { name: 'Scandinavian FX', volume: '$210 B', rawVolume: 6 },
        { name: 'Asian Currencies', volume: '$180 B', rawVolume: 5 },
      ],
      '1W': [
        { name: 'Major Pairs', volume: '24.1 T', rawVolume: 100 },
        { name: 'Minor Pairs', volume: '9.8 T', rawVolume: 43 },
        { name: 'Crosses', volume: '$6.2 T', rawVolume: 27 },
        { name: 'Commodity FX', volume: '$4.1 T', rawVolume: 18 },
        { name: 'Exotic Pairs', volume: '$2.8 T', rawVolume: 12 },
        { name: 'Scandinavian FX', volume: '$1.4 T', rawVolume: 6 },
        { name: 'Asian Currencies', volume: '$1.1 T', rawVolume: 5 },
      ],
      '1M': [
        { name: 'Major Pairs', volume: '98.5 T', rawVolume: 100 },
        { name: 'Minor Pairs', volume: '41.2 T', rawVolume: 44 },
        { name: 'Crosses', volume: '$25.4 T', rawVolume: 28 },
        { name: 'Commodity FX', volume: '$17.1 T', rawVolume: 18 },
        { name: 'Exotic Pairs', volume: '$11.2 T', rawVolume: 12 },
        { name: 'Scandinavian FX', volume: '$5.8 T', rawVolume: 6 },
        { name: 'Asian Currencies', volume: '$4.6 T', rawVolume: 5 },
      ],
      '1Y': [
        { name: 'Major Pairs', volume: '1.24 P', rawVolume: 100 },
        { name: 'Minor Pairs', volume: '512 T', rawVolume: 44 },
        { name: 'Crosses', volume: '$310 T', rawVolume: 28 },
        { name: 'Commodity FX', volume: '$210 T', rawVolume: 18 },
        { name: 'Exotic Pairs', volume: '$140 T', rawVolume: 12 },
        { name: 'Scandinavian FX', volume: '$72 T', rawVolume: 6 },
        { name: 'Asian Currencies', volume: '$58 T', rawVolume: 5 },
      ],
    },
    instruments: [
      {
        id: 'eurusd',
        name: 'Euro / US Dollar',
        symbol: 'EUR/USD',
        price: 1.0842,
        decimals: 4,
        change: 0.32,
        return1M: 1.45,
        rolVolume: 1.12,
        rsi: 52.4,
        marketCap: '$6.6T',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'fx-eur',
        iconBg: '#003399',
        iconColor: '#FFCC00',
      },
      {
        id: 'gbpusd',
        name: 'British Pound / USD',
        symbol: 'GBP/USD',
        price: 1.2954,
        decimals: 4,
        change: 0.48,
        return1M: 2.18,
        rolVolume: 1.35,
        rsi: 56.8,
        marketCap: '$3.2T',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'fx-gbp',
        iconBg: '#C8102E',
        iconColor: '#FFFFFF',
      },
      {
        id: 'usdjpy',
        name: 'USD / Japanese Yen',
        symbol: 'USD/JPY',
        price: 154.2,
        decimals: 2,
        change: -0.28,
        return1M: -1.12,
        rolVolume: 1.44,
        rsi: 46.2,
        marketCap: '$4.1T',
        signal: { type: 'neutral', text: 'Neutral 45%' },
        iconType: 'fx-jpy',
        iconBg: '#BC002D',
        iconColor: '#FFFFFF',
      },
      {
        id: 'audusd',
        name: 'Australian / US Dollar',
        symbol: 'AUD/USD',
        price: 0.6582,
        decimals: 4,
        change: 0.65,
        return1M: 3.1,
        rolVolume: 1.2,
        rsi: 58.1,
        marketCap: '$1.8T',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'fx-aud',
        iconBg: '#00843D',
        iconColor: '#FFCD00',
      },
      {
        id: 'usdcad',
        name: 'USD / Canadian Dollar',
        symbol: 'USD/CAD',
        price: 1.389,
        decimals: 4,
        change: -0.15,
        return1M: -0.84,
        rolVolume: 1.05,
        rsi: 49.3,
        marketCap: '$1.4T',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'fx-cad',
        iconBg: '#D80027',
        iconColor: '#FFFFFF',
      },
      {
        id: 'usdchf',
        name: 'USD / Swiss Franc',
        symbol: 'USD/CHF',
        price: 0.8845,
        decimals: 4,
        change: -0.22,
        return1M: -0.92,
        rolVolume: 0.98,
        rsi: 47.5,
        marketCap: '$1.1T',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'fx-chf',
        iconBg: '#FF0000',
        iconColor: '#FFFFFF',
      },
      {
        id: 'nzdusd',
        name: 'New Zealand / USD',
        symbol: 'NZD/USD',
        price: 0.592,
        decimals: 4,
        change: 0.51,
        return1M: 2.45,
        rolVolume: 1.15,
        rsi: 55.0,
        marketCap: '$890B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'fx-nzd',
        iconBg: '#00247D',
        iconColor: '#CC142B',
      },
      {
        id: 'eurgbp',
        name: 'Euro / British Pound',
        symbol: 'EUR/GBP',
        price: 0.837,
        decimals: 4,
        change: -0.14,
        return1M: -0.65,
        rolVolume: 1.08,
        rsi: 48.2,
        marketCap: '$1.5T',
        signal: { type: 'neutral', text: 'Neutral 45%' },
        iconType: 'fx-eur',
        iconBg: '#003399',
        iconColor: '#FFCC00',
      },
      {
        id: 'eurjpy',
        name: 'Euro / Japanese Yen',
        symbol: 'EUR/JPY',
        price: 167.22,
        decimals: 2,
        change: 0.05,
        return1M: 0.35,
        rolVolume: 1.25,
        rsi: 51.0,
        marketCap: '$1.2T',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'fx-jpy',
        iconBg: '#BC002D',
        iconColor: '#FFFFFF',
      },
      {
        id: 'gbpjpy',
        name: 'Pound / Japanese Yen',
        symbol: 'GBP/JPY',
        price: 199.75,
        decimals: 2,
        change: 0.21,
        return1M: 1.02,
        rolVolume: 1.38,
        rsi: 54.7,
        marketCap: '$980B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'fx-gbp',
        iconBg: '#C8102E',
        iconColor: '#FFFFFF',
      },
    ],
  },
  {
    id: 'indices',
    name: 'Indices CFDs',
    statValue: '$200.5T',
    statChange: '+0.45%',
    activity: '+$4.15',
    fearGreedScore: 72,
    fearGreedLabel: 'Greed',
    fearGreedColor: '#BEF226',
    entryVal: '+$2.0T  +0.45%',
    stopVal: '+$2.0T  +0.45%',
    allLiquidation: '$600.40 M',
    longVal: '$450.0M',
    shortVal: '$150.4M',
    openInterest: '+$2.0T  +0.45%',
    volumeVal: '+$2.0T  +0.45%',
    totalResults: 463,
    chartPoints: [
      15, 17, 18, 16, 19, 21, 24, 27, 25, 28, 30, 29, 31, 33, 35, 34, 37, 39, 38, 41, 43, 45, 44, 48,
    ],
    volumeComparison: {
      '1D': [
        { name: 'Stablecoin', volume: '48.52 B', rawVolume: 100 },
        { name: 'Bitcoin', volume: '28.45 B', rawVolume: 62 },
        { name: 'De-Fi', volume: '$6.12 B', rawVolume: 15 },
        { name: 'Meme', volume: '$4.89 B', rawVolume: 12 },
        { name: 'Layer 2', volume: '$3.15 B', rawVolume: 8 },
        { name: 'AI & DePIN', volume: '$1.78 B', rawVolume: 4.5 },
        { name: 'Game-Fi', volume: '$842.6 M', rawVolume: 2.2 },
      ],
      '1W': [
        { name: 'Stablecoin', volume: '310.2 B', rawVolume: 100 },
        { name: 'Bitcoin', volume: '185.4 B', rawVolume: 60 },
        { name: 'De-Fi', volume: '$42.1 B', rawVolume: 14 },
        { name: 'Meme', volume: '$31.8 B', rawVolume: 11 },
        { name: 'Layer 2', volume: '$21.5 B', rawVolume: 7.5 },
        { name: 'AI & DePIN', volume: '$12.4 B', rawVolume: 4.2 },
        { name: 'Game-Fi', volume: '$5.6 B', rawVolume: 2.1 },
      ],
      '1M': [
        { name: 'Stablecoin', volume: '1.24 T', rawVolume: 100 },
        { name: 'Bitcoin', volume: '740.5 B', rawVolume: 60 },
        { name: 'De-Fi', volume: '$168.2 B', rawVolume: 14 },
        { name: 'Meme', volume: '$124.6 B', rawVolume: 10.5 },
        { name: 'Layer 2', volume: '$86.2 B', rawVolume: 7.2 },
        { name: 'AI & DePIN', volume: '$49.8 B', rawVolume: 4.1 },
        { name: 'Game-Fi', volume: '$22.5 B', rawVolume: 2.0 },
      ],
      '1Y': [
        { name: 'Stablecoin', volume: '14.8 T', rawVolume: 100 },
        { name: 'Bitcoin', volume: '8.9 T', rawVolume: 60 },
        { name: 'De-Fi', volume: '$2.02 T', rawVolume: 14 },
        { name: 'Meme', volume: '$1.51 T', rawVolume: 10.5 },
        { name: 'Layer 2', volume: '$1.04 T', rawVolume: 7.2 },
        { name: 'AI & DePIN', volume: '$598 B', rawVolume: 4.1 },
        { name: 'Game-Fi', volume: '$270 B', rawVolume: 2.0 },
      ],
    },
    instruments: [
      {
        id: 'btc',
        name: 'Bitcoin',
        symbol: 'BTC/USD',
        price: 77204.0,
        decimals: 2,
        change: 0.85,
        return1M: 21.77,
        rolVolume: 1.34,
        rsi: 56.2,
        marketCap: '$1.54T',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'btc',
        iconBg: '#F7931A',
        iconColor: '#FFFFFF',
      },
      {
        id: 'eth',
        name: 'Ethereum',
        symbol: 'ETH/USD',
        price: 2514.85,
        decimals: 2,
        change: 3.17,
        return1M: 33.78,
        rolVolume: 1.72,
        rsi: 58.7,
        marketCap: '$297.46B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'eth',
        iconBg: '#627EEA',
        iconColor: '#FFFFFF',
      },
      {
        id: 'bnb',
        name: 'Binance',
        symbol: 'BNB/USD',
        price: 726.51,
        decimals: 2,
        change: 2.55,
        return1M: 19.03,
        rolVolume: 1.41,
        rsi: 55.4,
        marketCap: '$94.34B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'bnb',
        iconBg: '#F3BA2F',
        iconColor: '#000000',
      },
      {
        id: 'xmr',
        name: 'Monero',
        symbol: 'XMR/USD',
        price: 521.83,
        decimals: 2,
        change: 2.68,
        return1M: 32.99,
        rolVolume: 1.28,
        rsi: 61.3,
        marketCap: '$9.56B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'xmr',
        iconBg: '#FF6600',
        iconColor: '#FFFFFF',
      },
      {
        id: 'ltc',
        name: 'Litecoin',
        symbol: 'LTC/USD',
        price: 53.28,
        decimals: 2,
        change: 2.25,
        return1M: 18.72,
        rolVolume: 1.16,
        rsi: 57.1,
        marketCap: '$4.04B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'ltc',
        iconBg: '#345D9D',
        iconColor: '#FFFFFF',
      },
      {
        id: 'xrp',
        name: 'Ripple',
        symbol: 'XRP/USD',
        price: 1.36,
        decimals: 2,
        change: 2.26,
        return1M: 35.29,
        rolVolume: 1.53,
        rsi: 54.6,
        marketCap: '$83.88B',
        signal: { type: 'neutral', text: 'Neutral 45%' },
        iconType: 'xrp',
        iconBg: '#008CE7',
        iconColor: '#FFFFFF',
      },
      {
        id: 'pol',
        name: 'Polygon',
        symbol: 'POL/USD',
        price: 0.0974,
        decimals: 4,
        change: 5.74,
        return1M: 30.68,
        rolVolume: 1.88,
        rsi: 59.8,
        marketCap: '$986M',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'pol',
        iconBg: '#8247E5',
        iconColor: '#FFFFFF',
      },
      {
        id: 'avax',
        name: 'Avalance',
        symbol: 'AVAX/USD',
        price: 7.46,
        decimals: 2,
        change: 0.2,
        return1M: 18.09,
        rolVolume: 0.92,
        rsi: 48.9,
        marketCap: '$3.21B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'avax',
        iconBg: '#E84142',
        iconColor: '#FFFFFF',
      },
      {
        id: 'sol',
        name: 'Solana',
        symbol: 'SOL/USD',
        price: 102.39,
        decimals: 2,
        change: 3.81,
        return1M: 35.41,
        rolVolume: 1.67,
        rsi: 60.7,
        marketCap: '$57.83B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'sol',
        iconBg: '#000000',
        iconColor: '#14F195',
      },
      {
        id: 'uni',
        name: 'Uniswap',
        symbol: 'UNI/USD',
        price: 6.01,
        decimals: 2,
        change: 1.01,
        return1M: 68.14,
        rolVolume: 2.06,
        rsi: 67.2,
        marketCap: '$3.71B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'uni',
        iconBg: '#FF007A',
        iconColor: '#FFFFFF',
      },
      {
        id: 'nas100',
        name: 'Nasdaq 100 Index',
        symbol: 'NAS100/USD',
        price: 20412.5,
        decimals: 2,
        change: 1.15,
        return1M: 7.2,
        rolVolume: 1.68,
        rsi: 64.2,
        marketCap: '$22.8T',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'index-nas',
        iconBg: '#102A43',
        iconColor: '#38BEC9',
      },
      {
        id: 'us30',
        name: 'Dow Jones 30',
        symbol: 'US30/USD',
        price: 43210.0,
        decimals: 2,
        change: 0.42,
        return1M: 3.15,
        rolVolume: 1.18,
        rsi: 57.3,
        marketCap: '$14.1T',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'index-dow',
        iconBg: '#1B365D',
        iconColor: '#EAA221',
      },
      {
        id: 'ger40',
        name: 'DAX 40 Germany',
        symbol: 'GER40/EUR',
        price: 19450.8,
        decimals: 2,
        change: 0.55,
        return1M: 3.9,
        rolVolume: 1.25,
        rsi: 58.6,
        marketCap: '$1.9T',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'index-ger',
        iconBg: '#000000',
        iconColor: '#DD0000',
      },
      {
        id: 'uk100',
        name: 'FTSE 100 UK',
        symbol: 'UK100/GBP',
        price: 8245.3,
        decimals: 2,
        change: 0.31,
        return1M: 2.1,
        rolVolume: 1.08,
        rsi: 53.8,
        marketCap: '$2.4T',
        signal: { type: 'neutral', text: 'Neutral 45%' },
        iconType: 'index-uk',
        iconBg: '#012169',
        iconColor: '#C8102E',
      },
      {
        id: 'jpn225',
        name: 'Nikkei 225 Japan',
        symbol: 'JPN225/JPY',
        price: 38980.0,
        decimals: 2,
        change: 0.88,
        return1M: 5.4,
        rolVolume: 1.45,
        rsi: 62.0,
        marketCap: '$4.8T',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'index-jpn',
        iconBg: '#BC002D',
        iconColor: '#FFFFFF',
      },
      {
        id: 'hk50',
        name: 'Hang Seng Index',
        symbol: 'HK50/HKD',
        price: 20630.0,
        decimals: 2,
        change: -0.45,
        return1M: 8.6,
        rolVolume: 1.7,
        rsi: 52.1,
        marketCap: '$3.9T',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'index-hk',
        iconBg: '#DE2910',
        iconColor: '#FFDE00',
      },
      {
        id: 'estx50',
        name: 'Euro Stoxx 50',
        symbol: 'ESTX50/EUR',
        price: 4940.2,
        decimals: 2,
        change: 0.6,
        return1M: 4.25,
        rolVolume: 1.19,
        rsi: 56.4,
        marketCap: '$4.2T',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'index-eu',
        iconBg: '#003399',
        iconColor: '#FFCC00',
      },
      {
        id: 'us2000',
        name: 'Russell 2000',
        symbol: 'US2000/USD',
        price: 2240.1,
        decimals: 2,
        change: 1.4,
        return1M: 6.1,
        rolVolume: 1.55,
        rsi: 63.5,
        marketCap: '$3.1T',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'index-us',
        iconBg: '#0A2540',
        iconColor: '#F59E0B',
      },
      {
        id: 'fra40',
        name: 'CAC 40 France',
        symbol: 'FRA40/EUR',
        price: 7520.4,
        decimals: 2,
        change: 0.48,
        return1M: 2.85,
        rolVolume: 1.1,
        rsi: 54.2,
        marketCap: '$2.1T',
        signal: { type: 'neutral', text: 'Neutral 45%' },
        iconType: 'index-fr',
        iconBg: '#002395',
        iconColor: '#ED2939',
      },
    ],
  },
  {
    id: 'commodities',
    name: 'Commodities',
    statValue: '$94.6T',
    statChange: '+0.52%',
    activity: '+$2.90',
    fearGreedScore: 65,
    fearGreedLabel: 'Greed',
    fearGreedColor: '#84CC16',
    entryVal: '+$1.2T  +0.42%',
    stopVal: '+$1.2T  +0.42%',
    allLiquidation: '$390.10 M',
    longVal: '$270.0M',
    shortVal: '$120.1M',
    openInterest: '+$1.4T  +0.48%',
    volumeVal: '+$1.4T  +0.48%',
    totalResults: 42,
    chartPoints: [
      18, 19, 21, 20, 22, 25, 23, 27, 26, 29, 32, 31, 34, 36, 35, 38, 39, 41, 40, 43, 44, 46, 45, 47,
    ],
    volumeComparison: {
      '1D': [
        { name: 'Precious Metals', volume: '12.4 B', rawVolume: 100 },
        { name: 'Crude & Energy', volume: '9.8 B', rawVolume: 80 },
        { name: 'Industrial Metals', volume: '$4.2 B', rawVolume: 34 },
        { name: 'Agriculture Grains', volume: '$2.1 B', rawVolume: 17 },
        { name: 'Soft Commodities', volume: '$1.4 B', rawVolume: 12 },
        { name: 'Livestock Futures', volume: '$620 M', rawVolume: 5 },
        { name: 'Carbon Credits', volume: '$340 M', rawVolume: 3 },
      ],
      '1W': [
        { name: 'Precious Metals', volume: '81.4 B', rawVolume: 100 },
        { name: 'Crude & Energy', volume: '64.2 B', rawVolume: 79 },
        { name: 'Industrial Metals', volume: '$27.8 B', rawVolume: 34 },
        { name: 'Agriculture Grains', volume: '$14.2 B', rawVolume: 18 },
        { name: 'Soft Commodities', volume: '$9.4 B', rawVolume: 12 },
        { name: 'Livestock Futures', volume: '$4.1 B', rawVolume: 5 },
        { name: 'Carbon Credits', volume: '$2.2 B', rawVolume: 3 },
      ],
      '1M': [
        { name: 'Precious Metals', volume: '340.2 B', rawVolume: 100 },
        { name: 'Crude & Energy', volume: '270.5 B', rawVolume: 80 },
        { name: 'Industrial Metals', volume: '$118.4 B', rawVolume: 35 },
        { name: 'Agriculture Grains', volume: '$58.9 B', rawVolume: 17 },
        { name: 'Soft Commodities', volume: '$39.2 B', rawVolume: 12 },
        { name: 'Livestock Futures', volume: '$17.1 B', rawVolume: 5 },
        { name: 'Carbon Credits', volume: '$9.4 B', rawVolume: 3 },
      ],
      '1Y': [
        { name: 'Precious Metals', volume: '4.2 T', rawVolume: 100 },
        { name: 'Crude & Energy', volume: '3.4 T', rawVolume: 81 },
        { name: 'Industrial Metals', volume: '$1.5 T', rawVolume: 36 },
        { name: 'Agriculture Grains', volume: '$720 B', rawVolume: 17 },
        { name: 'Soft Commodities', volume: '$480 B', rawVolume: 11 },
        { name: 'Livestock Futures', volume: '$210 B', rawVolume: 5 },
        { name: 'Carbon Credits', volume: '$120 B', rawVolume: 3 },
      ],
    },
    instruments: [
      {
        id: 'xauusd',
        name: 'Gold Spot',
        symbol: 'XAU/USD',
        price: 2658.45,
        decimals: 2,
        change: 0.82,
        return1M: 5.4,
        rolVolume: 1.55,
        rsi: 63.8,
        marketCap: '$17.8T',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'cmd-gold',
        iconBg: '#FFD700',
        iconColor: '#996515',
      },
      {
        id: 'xagusd',
        name: 'Silver Spot',
        symbol: 'XAG/USD',
        price: 31.85,
        decimals: 2,
        change: 1.95,
        return1M: 12.4,
        rolVolume: 1.82,
        rsi: 66.2,
        marketCap: '$1.8T',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'cmd-silver',
        iconBg: '#E5E7EB',
        iconColor: '#4B5563',
      },
      {
        id: 'usoil',
        name: 'WTI Crude Oil',
        symbol: 'USOIL/USD',
        price: 70.42,
        decimals: 2,
        change: -0.65,
        return1M: -3.1,
        rolVolume: 1.34,
        rsi: 48.5,
        marketCap: '$2.2T',
        signal: { type: 'neutral', text: 'Neutral 45%' },
        iconType: 'cmd-oil',
        iconBg: '#1F2937',
        iconColor: '#F59E0B',
      },
      {
        id: 'ukoil',
        name: 'Brent Crude Oil',
        symbol: 'UKOIL/USD',
        price: 74.2,
        decimals: 2,
        change: -0.58,
        return1M: -2.85,
        rolVolume: 1.28,
        rsi: 49.1,
        marketCap: '$2.6T',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'cmd-brent',
        iconBg: '#111827',
        iconColor: '#3B82F6',
      },
      {
        id: 'natgas',
        name: 'Natural Gas',
        symbol: 'NATGAS/USD',
        price: 2.84,
        decimals: 2,
        change: 2.15,
        return1M: 14.2,
        rolVolume: 1.95,
        rsi: 62.4,
        marketCap: '$480B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'cmd-gas',
        iconBg: '#0284C7',
        iconColor: '#FFFFFF',
      },
      {
        id: 'copper',
        name: 'High Grade Copper',
        symbol: 'COPPER/USD',
        price: 4.38,
        decimals: 2,
        change: 0.75,
        return1M: 6.1,
        rolVolume: 1.4,
        rsi: 57.8,
        marketCap: '$950B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'cmd-copper',
        iconBg: '#B87333',
        iconColor: '#FFFFFF',
      },
      {
        id: 'platinum',
        name: 'Platinum Spot',
        symbol: 'XPT/USD',
        price: 985.2,
        decimals: 2,
        change: 0.92,
        return1M: 4.8,
        rolVolume: 1.22,
        rsi: 54.6,
        marketCap: '$310B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'cmd-plat',
        iconBg: '#9CA3AF',
        iconColor: '#FFFFFF',
      },
      {
        id: 'palladium',
        name: 'Palladium Spot',
        symbol: 'XPD/USD',
        price: 1045.0,
        decimals: 2,
        change: 1.4,
        return1M: 8.25,
        rolVolume: 1.38,
        rsi: 58.2,
        marketCap: '$190B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'cmd-pall',
        iconBg: '#6B7280',
        iconColor: '#FFFFFF',
      },
      {
        id: 'wheat',
        name: 'US Wheat Futures',
        symbol: 'WHEAT/USD',
        price: 582.5,
        decimals: 2,
        change: -0.4,
        return1M: -1.8,
        rolVolume: 1.05,
        rsi: 47.0,
        marketCap: '$240B',
        signal: { type: 'neutral', text: 'Neutral 45%' },
        iconType: 'cmd-wheat',
        iconBg: '#F59E0B',
        iconColor: '#FFFFFF',
      },
      {
        id: 'coffee',
        name: 'Coffee Arabica',
        symbol: 'COFFEE/USD',
        price: 254.2,
        decimals: 2,
        change: 2.8,
        return1M: 18.4,
        rolVolume: 2.1,
        rsi: 71.5,
        marketCap: '$120B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'cmd-coffee',
        iconBg: '#78350F',
        iconColor: '#FFFFFF',
      },
    ],
  },
  {
    id: 'stocks',
    name: 'Stocks',
    statValue: '$118.2T',
    statChange: '+0.61%',
    activity: '+$5.10',
    fearGreedScore: 70,
    fearGreedLabel: 'Greed',
    fearGreedColor: '#BEF226',
    entryVal: '+$2.4T  +0.55%',
    stopVal: '+$2.4T  +0.55%',
    allLiquidation: '$520.80 M',
    longVal: '$380.0M',
    shortVal: '$140.8M',
    openInterest: '+$2.2T  +0.52%',
    volumeVal: '+$2.2T  +0.52%',
    totalResults: 520,
    chartPoints: [
      14, 16, 17, 19, 21, 24, 26, 25, 27, 30, 32, 35, 34, 36, 38, 41, 39, 42, 44, 46, 45, 48, 49, 52,
    ],
    volumeComparison: {
      '1D': [
        { name: 'Mega-Cap Tech', volume: '24.8 B', rawVolume: 100 },
        { name: 'Semiconductors', volume: '18.2 B', rawVolume: 74 },
        { name: 'Consumer & Retail', volume: '$8.4 B', rawVolume: 34 },
        { name: 'Healthcare & Pharma', volume: '$6.1 B', rawVolume: 25 },
        { name: 'Financial Services', volume: '$5.2 B', rawVolume: 21 },
        { name: 'Energy & Industrials', volume: '$3.8 B', rawVolume: 15 },
        { name: 'Biotechnology', volume: '$1.9 B', rawVolume: 8 },
      ],
      '1W': [
        { name: 'Mega-Cap Tech', volume: '162.4 B', rawVolume: 100 },
        { name: 'Semiconductors', volume: '119.8 B', rawVolume: 74 },
        { name: 'Consumer & Retail', volume: '$55.1 B', rawVolume: 34 },
        { name: 'Healthcare & Pharma', volume: '$40.2 B', rawVolume: 25 },
        { name: 'Financial Services', volume: '$34.0 B', rawVolume: 21 },
        { name: 'Energy & Industrials', volume: '$24.9 B', rawVolume: 15 },
        { name: 'Biotechnology', volume: '$12.4 B', rawVolume: 8 },
      ],
      '1M': [
        { name: 'Mega-Cap Tech', volume: '680.5 B', rawVolume: 100 },
        { name: 'Semiconductors', volume: '498.2 B', rawVolume: 73 },
        { name: 'Consumer & Retail', volume: '$230.4 B', rawVolume: 34 },
        { name: 'Healthcare & Pharma', volume: '$168.0 B', rawVolume: 25 },
        { name: 'Financial Services', volume: '$142.1 B', rawVolume: 21 },
        { name: 'Energy & Industrials', volume: '$104.5 B', rawVolume: 15 },
        { name: 'Biotechnology', volume: '$52.1 B', rawVolume: 8 },
      ],
      '1Y': [
        { name: 'Mega-Cap Tech', volume: '8.4 T', rawVolume: 100 },
        { name: 'Semiconductors', volume: '6.2 T', rawVolume: 74 },
        { name: 'Consumer & Retail', volume: '$2.8 T', rawVolume: 33 },
        { name: 'Healthcare & Pharma', volume: '$2.1 T', rawVolume: 25 },
        { name: 'Financial Services', volume: '$1.8 T', rawVolume: 21 },
        { name: 'Energy & Industrials', volume: '$1.3 T', rawVolume: 15 },
        { name: 'Biotechnology', volume: '$650 B', rawVolume: 8 },
      ],
    },
    instruments: [
      {
        id: 'aapl',
        name: 'Apple Inc.',
        symbol: 'AAPL/USD',
        price: 232.4,
        decimals: 2,
        change: 0.95,
        return1M: 6.2,
        rolVolume: 1.28,
        rsi: 59.4,
        marketCap: '$3.54T',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'stk-aapl',
        iconBg: '#000000',
        iconColor: '#FFFFFF',
      },
      {
        id: 'nvda',
        name: 'Nvidia Corp.',
        symbol: 'NVDA/USD',
        price: 138.8,
        decimals: 2,
        change: 3.12,
        return1M: 18.45,
        rolVolume: 2.15,
        rsi: 68.2,
        marketCap: '$3.41T',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'stk-nvda',
        iconBg: '#76B900',
        iconColor: '#FFFFFF',
      },
      {
        id: 'msft',
        name: 'Microsoft Corp.',
        symbol: 'MSFT/USD',
        price: 428.15,
        decimals: 2,
        change: 0.65,
        return1M: 4.1,
        rolVolume: 1.15,
        rsi: 57.6,
        marketCap: '$3.18T',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'stk-msft',
        iconBg: '#00A4EF',
        iconColor: '#FFFFFF',
      },
      {
        id: 'amzn',
        name: 'Amazon.com Inc.',
        symbol: 'AMZN/USD',
        price: 188.6,
        decimals: 2,
        change: 1.4,
        return1M: 8.75,
        rolVolume: 1.42,
        rsi: 62.1,
        marketCap: '$1.98T',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'stk-amzn',
        iconBg: '#FF9900',
        iconColor: '#146EB4',
      },
      {
        id: 'googl',
        name: 'Alphabet Inc.',
        symbol: 'GOOGL/USD',
        price: 166.2,
        decimals: 2,
        change: 0.8,
        return1M: 5.3,
        rolVolume: 1.2,
        rsi: 56.8,
        marketCap: '$2.05T',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'stk-googl',
        iconBg: '#4285F4',
        iconColor: '#FFFFFF',
      },
      {
        id: 'meta',
        name: 'Meta Platforms',
        symbol: 'META/USD',
        price: 585.0,
        decimals: 2,
        change: 1.85,
        return1M: 12.1,
        rolVolume: 1.55,
        rsi: 64.7,
        marketCap: '$1.48T',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'stk-meta',
        iconBg: '#0668E1',
        iconColor: '#FFFFFF',
      },
      {
        id: 'tsla',
        name: 'Tesla Inc.',
        symbol: 'TSLA/USD',
        price: 218.5,
        decimals: 2,
        change: 4.2,
        return1M: 15.8,
        rolVolume: 2.3,
        rsi: 65.3,
        marketCap: '$698B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'stk-tsla',
        iconBg: '#E82127',
        iconColor: '#FFFFFF',
      },
      {
        id: 'avgo',
        name: 'Broadcom Inc.',
        symbol: 'AVGO/USD',
        price: 178.4,
        decimals: 2,
        change: 1.9,
        return1M: 9.4,
        rolVolume: 1.48,
        rsi: 61.2,
        marketCap: '$834B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'stk-avgo',
        iconBg: '#CC092F',
        iconColor: '#FFFFFF',
      },
      {
        id: 'brkb',
        name: 'Berkshire Hathaway',
        symbol: 'BRK.B/USD',
        price: 452.1,
        decimals: 2,
        change: 0.25,
        return1M: 2.15,
        rolVolume: 0.88,
        rsi: 52.4,
        marketCap: '$985B',
        signal: { type: 'neutral', text: 'Neutral 45%' },
        iconType: 'stk-brk',
        iconBg: '#23292F',
        iconColor: '#FFFFFF',
      },
      {
        id: 'lly',
        name: 'Eli Lilly and Co.',
        symbol: 'LLY/USD',
        price: 915.2,
        decimals: 2,
        change: 0.7,
        return1M: 4.8,
        rolVolume: 1.1,
        rsi: 58.0,
        marketCap: '$870B',
        signal: { type: 'lock', text: '>50%' },
        iconType: 'stk-lly',
        iconBg: '#D52B1E',
        iconColor: '#FFFFFF',
      },
    ],
  },
];
